require("prototypes.entity.turrets")
require("prototypes.entity.wallrepair")
require("prototypes.entity.obelisk")
require("prototypes.entity.deep-pumpjack")
require("prototypes.recipe.high-temp-oil-processing")
